import type { TruthPack } from "../domain.js";

export const retainedbTruthPack: TruthPack = {
  brandSlug: "retaindb",
  brandName: "RetainDB",
  brandDescription: "Persistent memory infrastructure for AI products and agents.",
  publicVoice: {
    tone: "technical, direct, builder-native, proof-first, product-led, contrastive, confident without fluff",
    styleRules: [
      "Lead with the problem in plain language.",
      "Use short, direct sentences.",
      "Prefer outcome plus mechanism plus proof.",
      "Use contrast framing when it helps: without versus with, guesses versus grounded truth.",
      "Sound like shipping infra, not a strategy deck.",
      "Avoid hype, vagueness, and abstract positioning language.",
    ],
    preferredPhrases: [
      "persistent memory",
      "memory infrastructure",
      "grounded docs",
      "three calls",
      "works with any LLM",
      "zero rearchitecting",
      "measured proof",
      "numbers you can hold us to",
    ],
    forbiddenPhrases: [
      "magic memory",
      "best in the world",
      "perfect memory",
      "solves memory forever",
      "revolutionary",
      "game-changing",
    ],
    founderVoiceNotes: [
      "Sound like the person who built the system and can prove how it works.",
      "Lead with specifics, then the implication.",
      "Be assertive, simple, and concrete.",
      "Prefer product truth over abstract positioning language.",
    ],
  },
  systemVoice: {
    tone: "technical, structured, evidence-linked, orchestration-aware, safe for reuse across channels",
    styleRules: [
      "Keep facts, strategy, and copy separate.",
      "Use claim ids and qualifiers for every factual assertion.",
      "Prefer structured outputs over prose when storing intermediate reasoning.",
      "Use public-site voice for external assets and system voice for internal instructions.",
      "Block unsupported claims and route risk to approval instead of improvising.",
    ],
    preferredPhrases: [
      "claim registry",
      "proof pack",
      "memory scopes",
      "approval checkpoint",
      "scorecard",
      "channel fit",
    ],
    forbiddenPhrases: [
      "magic memory",
      "best in the world",
      "perfect memory",
      "solves memory forever",
    ],
    founderVoiceNotes: [
      "Use internal platform language only when the audience is technical enough for it.",
      "Keep internal guidance precise, auditable, and claim-linked.",
      "Do not let orchestration language leak into homepage copy unless it helps the builder understand the mechanism.",
    ],
  },
  claims: [
    {
      id: "retainedb-persistent-memory",
      category: "feature",
      status: "verified",
      text: "RetainDB gives AI products persistent recall across sessions and grounds answers in actual docs instead of model guesses.",
      sourceUrls: ["https://www.retaindb.com/"],
      sourceExcerpt: "Persistent recall across sessions, grounded in your actual docs - not model hallucinations.",
      requiredQualifiers: ["persistent recall", "actual docs"],
      allowedChannels: ["seo", "social", "outbound", "community", "reply", "partnership", "landing"],
      forbiddenVariants: ["RetainDB is stateless", "RetainDB only stores prompts"],
      owner: "product",
      metadata: { source: "homepage hero" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-grounded-docs",
      category: "proof",
      status: "verified",
      text: "RetainDB answers from your docs and stored memory, not from stale model guesses.",
      sourceUrls: ["https://www.retaindb.com/"],
      sourceExcerpt: "Answers from your docs. Not model guesses.",
      requiredQualifiers: ["your docs", "not model guesses"],
      allowedChannels: ["seo", "social", "outbound", "community", "reply", "partnership", "landing"],
      forbiddenVariants: ["RetainDB hallucinates on stored facts"],
      owner: "product",
      metadata: { source: "what it does" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-three-calls",
      category: "feature",
      status: "verified",
      text: "RetainDB plugs into an existing AI stack in three calls: remember, getContext, and runTurn or captureSession.",
      sourceUrls: ["https://www.retaindb.com/"],
      sourceExcerpt: "Three calls. Persistent memory.",
      requiredQualifiers: ["three calls"],
      allowedChannels: ["seo", "social", "outbound", "community", "reply", "partnership", "landing"],
      forbiddenVariants: ["RetainDB needs a full stack rewrite"],
      owner: "product",
      metadata: { source: "how it works" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-preference-recall-88",
      category: "benchmark",
      status: "verified",
      text: "RetainDB scored 88% preference recall on LongMemEval and positions that result as state of the art.",
      sourceUrls: ["https://www.retaindb.com/"],
      sourceExcerpt: "88% preference recall. SOTA on LongMemEval.",
      requiredQualifiers: ["88%", "preference recall", "longmemeval"],
      allowedChannels: ["seo", "social", "outbound", "community", "reply", "partnership", "landing"],
      forbiddenVariants: ["RetainDB has no benchmark proof"],
      owner: "engineering",
      metadata: { source: "benchmark section" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-overall-accuracy-79",
      category: "benchmark",
      status: "verified",
      text: "RetainDB reports 79% overall accuracy on the LongMemEval oracle split.",
      sourceUrls: ["https://www.retaindb.com/"],
      sourceExcerpt: "79% overall accuracy. LongMemEval oracle split.",
      requiredQualifiers: ["79%", "overall accuracy", "oracle split"],
      allowedChannels: ["seo", "social", "outbound", "community", "reply", "partnership", "landing"],
      forbiddenVariants: ["RetainDB has no measured accuracy"],
      owner: "engineering",
      metadata: { source: "benchmark hero stats" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-grounded-docs-zero-hallucination",
      category: "benchmark",
      status: "verified",
      text: "RetainDB reports a 0% hallucination rate on grounded docs in the published v1 benchmark material.",
      sourceUrls: ["https://www.retaindb.com/"],
      sourceExcerpt: "0% hallucination rate. Grounded docs. v1.",
      requiredQualifiers: ["0%", "grounded docs"],
      allowedChannels: ["seo", "social", "outbound", "community", "reply", "partnership", "landing"],
      forbiddenVariants: ["RetainDB hallucinates on grounded docs"],
      owner: "platform",
      metadata: { source: "benchmark hero stats" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-sub40-p95",
      category: "benchmark",
      status: "verified",
      text: "RetainDB publishes sub-40ms p95 global retrieval latency.",
      sourceUrls: ["https://www.retaindb.com/"],
      sourceExcerpt: "Sub-40ms p95 global latency.",
      requiredQualifiers: ["sub-40ms", "p95"],
      allowedChannels: ["seo", "social", "outbound", "community", "reply", "partnership", "landing"],
      forbiddenVariants: ["RetainDB is latency-unaware"],
      owner: "engineering",
      metadata: { source: "how it works" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-any-llm",
      category: "integration",
      status: "verified",
      text: "RetainDB works with any LLM and explicitly names OpenAI, Anthropic, and Gemini on the public site.",
      sourceUrls: ["https://www.retaindb.com/"],
      sourceExcerpt: "Works with any LLM.",
      requiredQualifiers: ["works with any llm"],
      allowedChannels: ["seo", "social", "outbound", "community", "reply", "partnership", "landing"],
      forbiddenVariants: ["RetainDB only works with one model provider"],
      owner: "platform",
      metadata: { source: "integration surface" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-zero-rearchitecting",
      category: "integration",
      status: "verified",
      text: "RetainDB offers SDK, MCP, and Memory Router integration paths, with no rearchitecting required.",
      sourceUrls: ["https://www.retaindb.com/"],
      sourceExcerpt: "Works with how you already ship. Zero rearchitecting.",
      requiredQualifiers: ["zero rearchitecting"],
      allowedChannels: ["seo", "social", "outbound", "community", "reply", "partnership", "landing"],
      forbiddenVariants: ["RetainDB requires a rewrite"],
      owner: "platform",
      metadata: { source: "integrations" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-canonical-memory-api",
      category: "feature",
      status: "verified",
      text: "RetainDB exposes canonical memory endpoints on /v1/memory* and keeps legacy compatibility routes available.",
      sourceUrls: ["https://context.retaindb.com/docs"],
      sourceExcerpt: "Canonical memory API: use /v1/memory* endpoints.",
      requiredQualifiers: ["canonical", "memory"],
      allowedChannels: ["seo", "community", "outbound", "partnership"],
      forbiddenVariants: ["RetainDB only has legacy memory routes"],
      owner: "product",
      metadata: { source: "api docs" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-tree-search",
      category: "feature",
      status: "verified",
      text: "RetainDB includes Oracle tree search for hierarchical document navigation and research workflows.",
      sourceUrls: ["https://context.retaindb.com/docs"],
      sourceExcerpt: "Unique features like Oracle tree search.",
      requiredQualifiers: ["oracle", "tree search"],
      allowedChannels: ["seo", "community", "outbound", "partnership"],
      forbiddenVariants: ["RetainDB is just vector search"],
      owner: "product",
      metadata: { source: "comparison docs" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-memory-model",
      category: "feature",
      status: "verified",
      text: "RetainDB models seven memory types plus versioning, decay, consolidation, and relations.",
      sourceUrls: ["https://context.retaindb.com/docs"],
      sourceExcerpt: "Rich memory model: 7 types plus versioning and decay.",
      requiredQualifiers: ["seven memory types", "versioning"],
      allowedChannels: ["seo", "community", "outbound", "partnership"],
      forbiddenVariants: ["RetainDB is a single blob of notes"],
      owner: "product",
      metadata: { source: "comparison docs" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
    {
      id: "retainedb-canonical-mcp-surface",
      category: "feature",
      status: "verified",
      text: "RetainDB exposes a canonical MCP surface across context, memory, research, indexing, and code capabilities.",
      sourceUrls: ["https://context.retaindb.com/docs"],
      sourceExcerpt: "Canonical MCP surface: context.*, memory.*, research.oracle, index.*, code.*",
      requiredQualifiers: ["mcp"],
      allowedChannels: ["seo", "community", "outbound", "partnership"],
      forbiddenVariants: ["RetainDB lacks MCP support"],
      owner: "platform",
      metadata: { source: "contract registry" },
      lastVerifiedAt: "2026-03-22T00:00:00.000Z",
    },
  ],
  brandMemory: [
    "Lead with the pain in plain language, then show the mechanism.",
    "Use short, punchy lines and contrast framing: without versus with, guesses versus grounded truth.",
    "Homepage voice should sound builder-native and product-first, not like an internal platform spec.",
    "Public copy should center persistent memory, grounded docs, three calls, works with any LLM, zero rearchitecting, and measured proof.",
    "Internal orchestration copy can use claim registry, scorecards, and approval checkpoints, but that language should not dominate homepage assets.",
  ],
  marketMemory: [
    "Memory buyers respond to before and after contrast more than abstract platform language.",
    "Common objections: build it yourself, benchmark numbers do not translate, and memory is just another retrieval layer.",
    "The strongest wedge is persistent memory plus grounded docs plus measured proof, all without rearchitecting.",
  ],
  performanceMemory: [
    "Track which contrast hooks drive replies, not just impressions.",
    "Keep the best-performing proof-led phrases per persona and channel.",
  ],
  forbiddenClaims: [
    "RetainDB is the best memory system in the world.",
    "RetainDB solves memory forever.",
    "RetainDB never loses context.",
    "RetainDB is magic.",
  ],
};
